Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -56,7 +56,13 @@ jobs:
 
       - name: Terraform Validate
         id: validate
-        run: terraform validate -no-color
+        run: |
+          terraform validate -no-color -input=false
+          if [ $? -eq 0 ]; then
+              echo "Validation successful"
+          else
+              echo "Validation failed"
+          fi
 
       - name: Terraform Plan
         id: plan
